### ISSUE TITLE
CVE-2024-25767

### ISSUE THREAD

**Issue by JaylinYu** [LuMingYinDetect/nanomq_defects#1]
Hi， I am maintainer of NanoMQ, would like to get more information  regarding CVE-2024-25767.
Do you have any testing program to reproduce this issue? 

Would be better if you can confirm with us or nng about this issue before publishing it.

**Comment by LuMingYinDetect** [comment]
Hello! First of all, I apologize deeply for any inconvenience this may have caused. I am a graduate student specializing in static analysis. My usual work involves using the static analysis tool CSA to discover vulnerabilities in open-source projects. Static analysis may sometimes produce false positives, and the confirmation of vulnerabilities is done manually by me. Recently, my tool detected what seemed to be a UAF (Use After Free) vulnerability in NanoMQ, and I applied for a CVE for it. I'm sorry that I didn't submit the vulnerability information to you before applying for the CVE. This is because it's my first time dealing with vulnerability discovery, and as my research focuses on static analysis, I don't have something like test cases to trigger the defects. However, I have found the complete error path provided by CSA at the time for your reference. Once again, I apologize for any inconvenience caused.
Yours sincerely,
Mike

**Comment by JaylinYu** [comment]
No need to apologize for pointing out issues, we can improve our project by listening to the community. 
Seems like this is a bug, due to github synchronizing issue. Now it is fixed

**Comment by JaylinYu** [comment]
BTW, There is simply no way to trigger this bug in NanoMQ, we don't do sock close.

**Comment by LuMingYinDetect** [comment]
Thank you for your response. Although this bug won't trigger in nanomq, I'm still glad to contribute to identifying flaws in NanoNNG!
